export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const AUTH_LOADING = "AUTH_LOADING";
export const LOADING = "LOADING";
export const ADMIN_DATA = "ADMIN_DATA";

export const GET_ALL_PARENTCATEGORIES = "GET_ALL_PARENTCATEGORIES";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORY";
export const GET_ALL_STORIES = "GET_ALL_STORIES";
export const PAGE_COUNT = "PAGE_COUNT";

export const GET_WEEKLY_ALL_USERS_UNREGISTER =
  "GET_WEEKLY_ALL_USERS_UNREGISTER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_WEEKLY_ALL_USERS = "GET_WEEKLY_ALL_USERS";
export const GET_USERS_MSG = "GET_USERS_ERROR_MSG";
export const WEEKLY_FAMILY_MEMBER = "WEEKLY_FAMILY_MEMBER";
export const WEEKLY_JOURNAL = "WEEKLY_JOURNAL";
export const ALL_COUNT = "ALL_COUNT";
export const ALL_COUNT_LOADING = "ALL_COUNT_LOADING";

export const GET_JOURNALS = "GET_JOURNALS";
export const JOURNALS_LOADING = "JOURNALS_LOADING";
export const GET_FAMILTY_MEMBERS = "GET_FAMILTY_MEMBERS";

export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_DATA = "NOTIFICATION_DATA";
